# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_mainWindow(object):
    def setupUi(self, mainWindow: QtWidgets.QMainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(837, 592)
        mainWindow.setMinimumSize(837, 592)
        mainWindow.setMaximumSize(837, 592)
        mainWindow.setWindowIcon(QIcon("./logo.png"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setStyleSheet("color: white;")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 841, 591))
        self.widget.setObjectName("widget")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 190, 741, 271))
        self.textBrowser.setStyleSheet("border: 0px;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 150, 841, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(300, 480, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, -1, 841, 81))
        self.frame.setStyleSheet("background-color: #fb5b5d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 7, 841, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Исполнение желаний"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; color:#ffffff;\">Относительно молодой метод работы с подсознанием человека, автором которого является знаменитая </span><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; font-weight:600; color:#ffffff;\">Елена Блин</span><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; color:#ffffff;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; color:#ffffff;\">Согласно задумке автора, участники должны переносить на лист бумаги </span><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; font-weight:600; color:#ffffff;\">свои самые сокровенные мечты</span><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; color:#ffffff;\">, выражая их в рисунках, и тогда в своих головах они уже будут </span><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; font-weight:600; color:#ffffff;\">значительно ближе к их осуществлению</span><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; color:#ffffff;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft JhengHei Light\'; font-size:11pt; font-weight:600; color:#ffffff;\">Вам лишь нужно указать, какие мечты вы хотели бы осуществить, и нарисовать что угодно! Попробуйте, это бесплатно.</span></p></body></html>"))
        self.label_2.setText(_translate("mainWindow", "Как это работает?"))
        self.pushButton.setText(_translate("mainWindow", "Далее"))
        self.label.setText(_translate("mainWindow", "Добро пожаловать в приложение по созданию желаний"))